env:
  global:
    - HUGO_VERSION="0.59.0"

install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xzvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin
  - hugo version

script:
  - sed -i 's#^baseURL.*$#baseURL = "https://lucylucy83.github.io/"#' config.toml
  - hugo --gc --minify

deploy:
  provider: pages
  local_dir: public
  repo: lucylucy83/lucylucy83.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
~
