baseURL = "https://www.myskinin.com"
languageCode = "en-us"
title = "MySkinin | Skincare Insights"
theme = "myskinin-blog"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/headroom/headroom.js"
  [[params.plugins.js]]
  URL = "plugins/instafeed/instafeed.min.js"
  [[params.plugins.js]]
  URL = "plugins/masonry/masonry.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/smooth-scroll/smooth-scroll.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  

  
# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3

[params]
logo = "images/logo.webp"
home = "Home"
# hompage layout ( two layout is available,  you can set the another layout by change the value of homeLayoutToggle "true" to "false")
homeLayoutToggle = true
# Meta data
description = "Want to know how to get perfect skin? We know how to get flawless skin. Get skin care advice based on real insight, not Photoshopped images. Read our blog for more details."
# about author
author = "MySkinin"
authorImage = "scincare-advice-experts"
shortDescription = "We share decades of skin care obsession with you. No edited before/after photos and make you believe that we recommend miraculous cures. We only share with you logic and reasons for why what we recommend works."
# Contact Form Action
contactFormAction = "#"
# Google Analitycs
googleAnalitycsID = "UA-152586290-1"
# copyright
copyright = "MySkinin.com"

  # Preloader
  [params.preloader]
  enable = false
  
  # search
  [params.search]
  enable = true

  # Instagram feed
  [params.instafeed]
  enable = false
  userID = "4044026246"
  accessToken = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"

  # footer
  [params.footer]

    #address
    [[params.footer.addresses]]
    address = "London"
    
    [[params.footer.addresses]]
    address = "United Kingdom"

    
    #contact information
    [[params.footer.contacts]]
    contactInfo = "Tel: Coming Soon!"
    
    [[params.footer.contacts]]
    contactInfo = "Mail: myskinin@gmail.com"


  # social site
  #[[params.social]]
  #icon = "ti-facebook"
  #URL = "https://www.facebook.com/"
  
  #[[params.social]]
  #icon = "ti-twitter-alt"
  #URL = "www.twitter.com/"
  

  [[params.social]]
  icon = "ti-instagram"
  URL = "https://www.instagram.com/myskinin"
